IF OBJECT_ID ('Funcionario', 'U') IS NOT NULL
DROP TABLE Funcionario;

CREATE TABLE Funcionario
(
	CODFUNC     INT IDENTITY(1,1) NOT NULL,
	NOME        VARCHAR(50)       NOT NULL,
	CPF         INT               NOT NULL,
	NUMHORASMES INT,
	SALARIO     NUMERIC(5,2),
)
GO

ALTER TABLE Funcionario
	ADD CONSTRAINT PK_FUNCIONARIO
		PRIMARY KEY(CODFUNC);

ALTER TABLE Funcionario
	ADD CONSTRAINT UNIQUE_FUNCIONARIO_CPF
		UNIQUE(CPF);

ALTER TABLE Funcionario
	ADD CONSTRAINT CHK_FUNCIONARIO_SALARIO
		CHECK(SALARIO > 0);

IF OBJECT_ID ('Ponto', 'U') IS NOT NULL
DROP TABLE Ponto;
CREATE TABLE Ponto
(
	CODFUNC      INT      NOT NULL,
	DTLANCAMENTO DATETIME NOT NULL,
	LANCENTRADA  TIME     NULL,
	LANCSAIDA    TIME     NULL,
)
GO

ALTER TABLE Ponto
	ADD CONSTRAINT FK_CODFUNC
		FOREIGN KEY(CODFUNC)
			REFERENCES Funcionario(CODFUNC);
