CREATE DATABASE Ponto

CREATE TABLE Funcionario
(
	CODFUNC  INT NOT NULL UNIQUE,
	NOME     VARCHAR(50) not null,
	PRIMARY KEY (codFunc)
	
);

CREATE TABLE Ponto
(
	CODFUNC      INT NOT NULL,
	DTLANCAMENTO DATETIME NOT NULL,
	LANCENTRADA  DATETIME NULL,
	LANCSAIDA    DATETIME NULL,
	FOREIGN KEY (codFunc) REFERENCES Funcionario
);
